inherit_from:
  - .rubocop_airbnb.yml

#rubocopでコード解析したくないファイルやフォルダを指定
AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'
    - 'node_modules/slick-carousel/slick/config.rb'
    
Style/RedundantSelf:
  Enabled: false
  
Layout/IndentationConsistency:
  Enabled: false
  
Layout/LineLength:
  Max: 150
  
Rails/RedundantForeignKey:
  Enabled: false